name: Centralized book generation

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    uses: SquareBracketAssociates/BookBuilderDashboard/.github/workflows/main.yml@master
    with:
      bookname: PharoCatalog